name: flutter_offline_queue
description: flutter_offline_queue is a Flutter/Dart package to queue API requests offline and retry when online.
version: 1.0.1
repository: https://github.com/Mohammad-AD/offline_queue

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  connectivity_plus: ^6.1.4
  sqflite: ^2.4.2
  path: ^1.9.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
